title = "СпортоЛюбитель"
baseURL = "https://example.com"
languageCode = "ru-ru"
languageName = "Русский"
pluralizeListTitles = false
theme = "ananke"
enableEmoji = true
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "ru"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Заметки не профессионального физкультурника"
  facebook = ""
  twitter = "https://twitter.com/toparvion"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  strava = "https://www.strava.com/athletes/26082931"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/running-on-aquathlon.jpg"
  recent_posts_number = 3
  body_classes = "athelas bg-near-white"
