title = "СпортоЛюбитель"
baseURL = "https://toparvion.run"
languageCode = "ru-ru"
languageName = "Русский"
pluralizeListTitles = false
theme = "ananke-toparvion"
enableEmoji = true
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "ru"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
disqusShortname = "toparvion-run"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/decor/favicon.png"
  description = "Заметки не профессионального физкультурника"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  strava = "https://www.strava.com/athletes/toparvion"
  background_color_class = "bg-black"
  featured_image = "/images/decor/running-on-aquathlon.jpg"
  recent_posts_number = 3
  body_classes = "athelas bg-near-white"
